branch-defaults:
  main:
    environment: Test-env
environment-defaults:
  Test-env:
    branch: null
    repository: null
  mysite-env:
    branch: null
    repository: null
global:
  application_name: Test
  default_ec2_keyname: swe1-eb
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
